Depend on camptocamp/systemd ~> 3.1
theforeman/puppet-dhcp pull request #202
Opened 2021-09-21 09:04 UTC by ekohl

In 8ab95bcd65cdb83f8d1ca4d5b4473880b6737eb7 a change was made that required at least version 3.1.0. This fixes the metadata to reflect that.

2021-09-21 09:10 UTC, evgeni commented
Technically, there is no such version.

https://forge.puppet.com/modules/camptocamp/systemd maxes out at 3.0.0, and newer ones are at https://forge.puppet.com/modules/puppet/systemd

Should we reflect that too?

2021-09-21 09:12 UTC, ekohl commented
I just came to the same conclusion. It'd be the right thing to do (and solve https://github.com/theforeman/puppet-puppet/issues/802). Looking at our installer, only puppet/redis is outside of our namespace so it should be fairly easy to move.

2021-09-21 10:18 UTC, evgeni commented
Out of curiosity, what happens if we ask librarian to install `camptocamp/systemd` (via some dependency) and `puppet/systemd`?

2021-09-21 10:21 UTC, evgeni requested changes

2021-09-21 10:21 UTC, evgeni commented on .fixtures.yml
> +    systemd:     'https://github.com/puppet/puppet-systemd'
```suggestion
    systemd:     'https://github.com/voxpupuli/puppet-systemd'
```

2021-09-21 10:25 UTC, ekohl commented
We should coordinate merging these PRs in order not to break our nightly builds.
```
$ rg systemd _build/modules/*/metadata.json
_build/modules/systemd/metadata.json
2:  "name": "camptocamp-systemd",
7:  "source": "https://github.com/camptocamp/puppet-systemd",
8:  "project_page": "https://github.com/camptocamp/puppet-systemd",
9:  "issues_url": "https://github.com/camptocamp/puppet-systemd/issues",

_build/modules/redis/metadata.json
16:      "name": "camptocamp/systemd",

_build/modules/qpid/metadata.json
20:      "name": "camptocamp/systemd",

_build/modules/puppet/metadata.json
31:      "name": "camptocamp/systemd",

_build/modules/pulpcore/metadata.json
30:      "name": "camptocamp/systemd",

_build/modules/foreman/metadata.json
16:      "name": "camptocamp/systemd",

_build/modules/dhcp/metadata.json
19:      "name": "camptocamp/systemd",
```

* Redis should switch with version 8; foreman and pulpcore need to allow that
* https://github.com/theforeman/puppet-qpid/pull/173
* https://github.com/theforeman/puppet-pulpcore/pull/228
* https://github.com/theforeman/puppet-puppet/pull/804
* https://github.com/theforeman/puppet-foreman/pull/997

2021-09-21 10:26 UTC, ekohl commented
> Out of curiosity, what happens if we ask librarian to install `camptocamp/systemd` (via some dependency) and `puppet/systemd`?

I think it should fail but I'm not sure tbh.

2021-09-21 11:13 UTC, jovandeginste commented
It picks one

2021-09-21 11:15 UTC, jovandeginste commented
If two modules disagree, librarian picks one; you can override by specifying it in your own Puppetfile. You should also "fix" the Puppetfile.lock

2021-10-20 19:56 UTC, ehelms approved these changes

2021-10-21 14:06 UTC, merged